name: CI

on:
    push:
        branches: [ main ]
    
jobs:
    deploy:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
          - run: cd backend
          - run: npm install
          - run: npm run build --if-present
