name: CI

on:
    push:
        branches: [ main ]
    
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js 16
            uses: actions/setup-node@v1
            with:
                node-version: 16
          - run: cd backend
          - run: npm install
          - run: npm run build --if-present
